### ISSUE TITLE
'raw' filter not being respected?

### ISSUE THREAD

**Issue by ericras** [unlcms/tims#22]
Problem is a double encoded ampersand.

Remove this template that bypasses using render() as a quick fix: http://unlcms-staging.unl.edu/fpa/admin/structure/tims/field__field_list_section_title/edit

See "FILM &amp; NEW MEDIA" section of http://unlcms-staging.unl.edu/fpa/theatre-and-film/faculty-staff for the double encoded '&'

That field is now passing through http://unlcms.unl.edu/fpa/admin/structure/tims/field/edit which should spit it out with "raw"

**Comment by tsteiner** [comment]
Dosen't seem to be an issue with TIMS.  I turned the module off, and the double-encoding was still happening.

**Comment by tsteiner** [comment]
It looks like the link module is calling check_plain() on the title

**Comment by tsteiner** [comment]
Yup: https://drupal.org/node/1040424
